/// A single lesson step inside a topic plan.
class PlanLesson {
  const PlanLesson({
    required this.index,
    required this.title,
    required this.durationMinutes,
    this.resource,
  });

  final int index;
  final String title;
  final int durationMinutes;

  /// Optional resource (URL or in-app route hint).
  final String? resource;
}

/// A full topic plan generated by Ералы (e.g. an IELTS preparation plan).
class TopicPlan {
  const TopicPlan({
    required this.topic,
    required this.lessons,
    this.notes = '',
  });

  final String topic;
  final List<PlanLesson> lessons;

  /// General notes or prerequisites.
  final String notes;
}

// ── Questionnaire state machine ───────────────────────────────────────────────

/// The questions Ералы asks before generating a plan.
enum PlanQuestion {
  resources,
  availableTime,
  internetAccess,
}

/// Collected answers for the pre-plan questionnaire.
class PlanQuestionnaire {
  const PlanQuestionnaire({
    this.resources,
    this.availableTime,
    this.internetAccess,
  });

  final String? resources;
  final String? availableTime;
  final bool? internetAccess;

  PlanQuestionnaire copyWith({
    String? resources,
    String? availableTime,
    bool? internetAccess,
  }) {
    return PlanQuestionnaire(
      resources: resources ?? this.resources,
      availableTime: availableTime ?? this.availableTime,
      internetAccess: internetAccess ?? this.internetAccess,
    );
  }

  bool get isComplete =>
      resources != null && availableTime != null && internetAccess != null;

  /// Returns the next unanswered question, or null if [isComplete].
  PlanQuestion? get nextQuestion {
    if (resources == null) return PlanQuestion.resources;
    if (availableTime == null) return PlanQuestion.availableTime;
    if (internetAccess == null) return PlanQuestion.internetAccess;
    return null;
  }
}
