import 'package:admity/core/theme/app_colors.dart';
import 'package:admity/core/theme/app_tokens.dart';
import 'package:admity/features/mentor/domain/topic_plan.dart';
import 'package:admity/shared/widgets/app_card.dart';
import 'package:admity/shared/widgets/app_scaffold.dart';
import 'package:flutter/material.dart';

// ── Topic Plan Screen ─────────────────────────────────────────────────────────
//
// Shows the lesson-by-lesson plan generated by Ералы.
// Per DESIGN_SYSTEM.md §8: SafeArea > SingleChildScrollView > Column(.min).

class TopicPlanScreen extends StatelessWidget {
  const TopicPlanScreen({required this.plan, super.key});

  final TopicPlan plan;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<AppTokens>() ?? AppTokens.defaults();

    return AppScaffold(
      appBar: AppBar(
        backgroundColor: AppColors.white,
        elevation: 0,
        title: Text(
          'План: ${plan.topic}',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
                color: AppColors.ink,
              ),
          overflow: TextOverflow.ellipsis,
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_rounded, color: AppColors.ink),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(tokens.screenPadding),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ── Header ─────────────────────────────────────────────────
            Text(
              plan.topic,
              style: Theme.of(context).textTheme.headlineLarge?.copyWith(
                    color: AppColors.ink,
                  ),
            ),
            SizedBox(height: tokens.gapSm),
            Text(
              '${plan.lessons.length} уроков',
              style: Theme.of(context).textTheme.bodySmall,
            ),
            if (plan.notes.isNotEmpty) ...[
              SizedBox(height: tokens.gapMd),
              AppCard(
                color: AppColors.surfaceTint,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Icon(
                      Icons.info_outline_rounded,
                      size: 18,
                      color: AppColors.primary,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        plan.notes,
                        style:
                            Theme.of(context).textTheme.bodySmall?.copyWith(
                                  color: AppColors.inkSecondary,
                                ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
            SizedBox(height: tokens.gapXl),

            // ── Lesson list ───────────────────────────────────────────
            ...plan.lessons.map(
              (lesson) => Padding(
                padding: EdgeInsets.only(bottom: tokens.gapMd),
                child: _LessonCard(lesson: lesson, tokens: tokens),
              ),
            ),

            SizedBox(height: tokens.gapXxl),
          ],
        ),
      ),
    );
  }
}

// ── Lesson card ───────────────────────────────────────────────────────────────

class _LessonCard extends StatelessWidget {
  const _LessonCard({required this.lesson, required this.tokens});

  final PlanLesson lesson;
  final AppTokens tokens;

  @override
  Widget build(BuildContext context) {
    return AppCard(
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Lesson index badge
          Container(
            width: 36,
            height: 36,
            decoration: const BoxDecoration(
              color: AppColors.primary,
              shape: BoxShape.circle,
            ),
            alignment: Alignment.center,
            child: Text(
              '${lesson.index}',
              style: const TextStyle(
                color: AppColors.white,
                fontWeight: FontWeight.w700,
                fontSize: 14,
              ),
            ),
          ),
          SizedBox(width: tokens.gapMd),
          Expanded(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  lesson.title,
                  style: Theme.of(context).textTheme.bodyLarge?.copyWith(
                        color: AppColors.ink,
                        fontWeight: FontWeight.w600,
                      ),
                ),
                SizedBox(height: tokens.gapXs),
                Row(
                  children: [
                    const Icon(
                      Icons.timer_outlined,
                      size: 14,
                      color: AppColors.inkSecondary,
                    ),
                    const SizedBox(width: 4),
                    Text(
                      '${lesson.durationMinutes} мин',
                      style: Theme.of(context).textTheme.bodySmall,
                    ),
                  ],
                ),
                if (lesson.resource != null) ...[
                  SizedBox(height: tokens.gapXs),
                  Row(
                    children: [
                      const Icon(
                        Icons.link_rounded,
                        size: 14,
                        color: AppColors.primary,
                      ),
                      const SizedBox(width: 4),
                      Expanded(
                        child: Text(
                          lesson.resource!,
                          style:
                              Theme.of(context).textTheme.bodySmall?.copyWith(
                                    color: AppColors.primary,
                                  ),
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                    ],
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }
}
